import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# OPENAI API KEY
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# TAVILY API KEY FOR SEARCH
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")

# MAILCHIMP CONFIGURATION
MAILCHIMP_API_KEY = os.getenv("MAILCHIMP_API_KEY")
MAILCHIMP_SERVER_PREFIX = os.getenv("MAILCHIMP_SERVER_PREFIX")
MAILCHIMP_LIST_ID = os.getenv("MAILCHIMP_LIST_ID")

# TWILIO CONFIGURATION (WHATSAPP/SMS)
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN")
TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER")
TO_PHONE_NUMBER = os.getenv("TO_PHONE_NUMBER")

# SMTP CONFIGURATION (EMAIL NOTIFICATIONS)
SMTP_SERVER = os.getenv("SMTP_SERVER")
SMTP_PORT = os.getenv("SMTP_PORT", 587)
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASS = os.getenv("SMTP_PASS")
TO_EMAIL = os.getenv("TO_EMAIL")

# DATABASE
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite:///leads.db")
